RCPin: 27
RelayOff: 0
RelayOn: 1
ackMessage: GGG
alivePin: 22
central_db_dbname: zone1centraldb
central_db_hostname: 192.168.0.201
central_db_password: zone1
central_db_username: zone1
dataPath: data/thdata.csv
db_dbname: zone1db
db_hostname: 127.0.0.1
db_password: zone1
db_username: zone1
emailEnabled: true
emailSendTimeGap: 900000
fanRelay: 13
fan_off_t: 60000
fan_on_t: 15000
hardware: RaspberryPi2
heartBeatInterval: 30000
heatExternalTDiffMs: 5000
heatInternalTDiffMs: 5000
heatOffMs: 30000
heatOnMs: 6000
heaterRelay: 5
heater_sp_offset: 0
id: g
led2: 4
locationDisplayName: GRG
maxSensorReadErrors: 3
min_CSV_write_interval: 6000000
mqttPublishIntervalMillis: 60000
mqttPublishTeleIntervalMillis: 120000
onlyPublishMQTTOnChange: true
outSideTempSensor: DS18B20-1
platform_name: RPi2
powerPin: 2
processUptime: 00:00:00
quietMode: true
radioChannel: 124
readDelay: 5
readingPipeAddress: NodeG
relay4: 6
remoteDBEnabled: false
sensorPin: 3
systemMessage: system message
systemUpTime: 00:00:00
tempAlertHi: 26.1
tempAlertLo: 13.0
tempSPLOff: 16.0
tempSPLOn: 24.0
ventDarkOffDelta: 10000
ventDarkOnDelta: 100000
ventDisableHumi: 65
ventDisableTemp: 18
ventEnableHighSpeed: false
ventOffDelta: 65000
ventOnDelta: 195000
ventPulseOnDelta: 30000
ventRelay: 26
vent_loff_sp_offset: 2.0
vent_lon_sp_offset: 0.0
version: Version Placeholder
watchDogPin: 17
writingPipeAddress: Node0
zoneName: Zone1
zoneNumber: '1'
