# YAML

#===config params to store in config obj so tunable via web interface====

#Zone 2 - RPi
tempSPLOn: 22.5   #target 22.5 mp set point max with lon
tempSPLOff: 15.3 #16.9 #target = 16.9, target loff

lightOnT: "21:00:00"    # time light on hh:mm:ss
lightOffT: "09:00:00"   # time off
## comment out for hardware used as appropriate
#platform_name: "RPi2"
##platformName = "PCDuino"
#hardware: "RaspberryPi2"
#hardware = "PCDuino"
#readDelay: 3
#min_CSV_write_interval: 1 * 60 * 1000 #interval min bet csv writes

##----L control params----
#on_hours: [ 21,22,23,0,1,2,3,4,5,6,7,8 ] #hours when l on
heat_off_hours: [ 21,22,23,0,1,2,3,4,5,6,7,8 ]   #hours when heater should NOT operate
##tlon_hour: 06
##tlon_minute: 0    # time on
##tloff_hour: 18
##tloff_minute: 0   # time off

RelayOff: 1 #state for relay OFF
RelayOn: 0  #state for on

#testDivisor: 1 #divisor to speed up sequencing to test timings

heater_on_t: 20000  #min time heater is on or off for
heater_off_t: 97000  #min time heater is on or off for
heater_sp_offset: 0

#ventOnDelta: 3 * 1000 / testDivisor   #duration vent is on in millis
#ventOffDelta: 197 * 1000 / testDivisor  #vent off duration in miili sec
#ventPulseOnDelta: 10 * 1000 #60 secs cooling on delta
#vent_lon_sp_offset: 0.0 #offset
#vent_loff_sp_offset: 1.0 #

#fan_on_t: 29 * 60 * 1000 / testDivisor   #vent on time
##fan_on_t = 30 * 1000 / testDivisor   #vent on time

#fan_off_t: 10 * 1000 / testDivisor #vent off time

#dataPath: "data/thdata.csv"
#extraPath: "data/extradata.csv"

#emailEnabled: False

#tSPHi: temp_d_on_SP
#tSPLo: temp_d_off_SP

##db params
#db_hostname: "127.0.0.1"
#db_username: "controller"
#db_password: "password"
#db_dbname: "sensordata_db"

#hi_temp_warning: 26.0
#lo_temp_warning: 14.0



#central_db_hostname: "192.168.0.201"
#central_db_username: "myiot"
#central_db_password: "myiot"
#central_db_dbname: "zone1_sensordata_db"
