# YAML

#===config params to store in config obj so tunable via web interface====

#Zone 2 - PCDuino
#Hardware specific config items
# comment out for hardware used as appropriate
#platform_name: "RPi2"
platform_name: "PCDuino"
#hardware: "RaspberryPi2"
hardware: "PCDuino"
readDelay: 3

tempSPLOn: 24.0   #target 22.5 mp set point max with lon
tempSPLOff: 21.0 #16.9 #target = 16.9, target loff

lightOnT: "14:00:00"    # time light on hh:mm:ss
lightOffT: "20:00:00"   # time off

## comment out for hardware used as appropriate

min_CSV_write_interval: 60000 #interval min bet csv writes

##----L control params----
heat_off_hours: [ 20 ]   #hours when heater should NOT operate


RelayOff: 1 #state for relay OFF
RelayOn: 0  #state for on


heater_on_t: 18000 #min time heater is on or off for
heater_off_t: 113000 #min time heater is on or off for
heater_sp_offset: 0

ventOnDelta: 3000   #duration vent is on in millis
ventOffDelta: 197000 #vent off duration in miili sec
ventPulseOnDelta: 10000 #60 secs cooling on delta
vent_lon_sp_offset: 0.0 #offset
vent_loff_sp_offset: 1.0 #

fan_on_t: 5000    #vent on time ms
#fan_on_t = 30 * 1000 / testDivisor   #vent on time
fan_off_t: 45000 #vent off time ms

dataPath: "data/thdata.csv"
extraPath: "data/extradata.csv"

emailEnabled: False


#db params
db_hostname: "127.0.0.1"
db_username: "root"
db_password: "ubuntu"
db_dbname: "sensordata_db"

central_db_hostname: "192.168.0.201"
central_db_username: "myiot"
central_db_password: "myiot"
central_db_dbname: "zone2_sensordata_db"
