# YAML

#===config params to store in config obj so tunable via web interface====

#Zone 1 - RPi
zoneName: "Zone 1"

#Hardware specific config items
# comment out for hardware used as appropriate
platform_name: "RPi2"
#platform_name = "PCDuino"
hardware: "RaspberryPi2"
#hardware = "PCDuino3"
readDelay: 3 #sensor read delay
##
tempSPLOn: 21.0   #target 22.5 mp set point max with lon
tempSPLOff: 15.0 #16.9 #target = 16.9, target loff

tempAlertHi: 26.1  #hi temp alert temp
tempAlertLo: 15.0  #lo temp alert

lightOnT: "21:00:00"    # time light on hh:mm:ss
lightOffT: "09:00:00"   # time off

min_CSV_write_interval: 60000 #interval min bet csv writes

##----L control params----
heat_off_hours: [ 22,23,0,1,2,3,4,5,6,7,8,9,10 ]   #hours when heater should NOT operate

RelayOff: 1 #state for relay OFF
RelayOn: 0  #state for on

heater_on_t: 10000  #min time heater is on or off for
heater_off_t: 30000  #min time heater is on or off for
heater_sp_offset: 0

ventOnDelta: 20000 #duration vent is on in millis
ventOffDelta: 97000 #vent off duration in miili sec
ventPulseOnDelta: 20000 #60 secs cooling on delta
vent_lon_sp_offset: -0.1 #offset
vent_loff_sp_offset: 1.0 #

fan_on_t: 1800000  #vent on time
fan_off_t: 1000 #vent off time

dataPath: "data/thdata.csv"
#extraPath: "data/extradata.csv"

emailEnabled: True

#db params
db_hostname: "127.0.0.1"
db_username: "controller"
db_password: "password"
db_dbname: "sensordata_db"

central_db_hostname: "192.168.0.201"
central_db_username: "myiot"
central_db_password: "myiot"
central_db_dbname: "zone1_sensordata_db"

#placeholder items - used for items pushed from system
processUptime: "00:00:00"
systemMessage: "system message"
systemUpTime: "00:00:00"
version: "Version Placeholder"

