false: 1
true: 0
central_db_dbname: zone1_sensordata_db
central_db_hostname: 192.168.0.201
central_db_password: myiot
central_db_username: myiot
dataPath: /home/pi/controlleroo/data/thdata.csv
db_dbname: sensordata_db
db_hostname: 127.0.0.1
db_password: password
db_username: controller
emailEnabled: false
extraPath: /home/pi/controlleroo/data/extradata.csv
fan_off_t: 10 * 1000 / testDivisor
fan_on_t: 29 * 60 * 1000 / testDivisor
hardware: RaspberryPi2
heat_off_hours: [21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8]
heater_off_t: 113 * 1000 / testDivisor
heater_on_t: 18 * 1000 / testDivisor
heater_sp_offset: 0
hi_temp_warning: 26.0
lightOffT: 09:00:00
lightOnT: '21:00:00'
lo_temp_warning: 14.0
min_CSV_write_interval: 1 * 60 * 1000
on_hours: [21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8]
platform_name: RPi2
readDelay: 3
tSPHi: temp_d_on_SP
tSPLo: temp_d_off_SP
tempSPLOff: 15.3
tempSPLOn: 22.5
testDivisor: 1
ventOffDelta: 197 * 1000 / testDivisor
ventOnDelta: 3 * 1000 / testDivisor
ventPulseOnDelta: 10 * 1000
vent_loff_sp_offset: 1.0
vent_lon_sp_offset: 0.0
