RCPin: 27
RelayOff: 0
RelayOn: 1
ackMessage: SSS
alivePin: 22
central_db_dbname: zone3centraldb
central_db_hostname: 192.168.0.201
central_db_password: zone3
central_db_username: zone3
dataPath: data/thdata.csv
db_dbname: zone3db
db_hostname: 127.0.0.1
db_password: zone3
db_username: zone3
emailEnabled: true
emailSendTimeGap: 900000
fanRelay: 13
fan_off_t: 60000
fan_on_t: 60000
hardware: RaspberryPi2
heartBeatInterval: 30000
heatExternalTDiffMs: 5000
heatInternalTDiffMs: 5000
heatOffMs: 10000
heatOnMs: 5000
heaterRelay: 5
heater_sp_offset: 0
id: s
led2: 4
locationDisplayName: SHD
maxSensorReadErrors: 3
min_CSV_write_interval: 6000000
mqttPublishIntervalMillis: 60000
mqttPublishTeleIntervalMillis: 120000
onlyPublishMQTTOnChange: true
outSideTempSensor: DS18B20-1
platform_name: RPi2
powerPin: 2
processUptime: 00:00:00
quietMode: true
radioChannel: 124
readDelay: 5
readingPipeAddress: NodeS
relay4: 6
remoteDBEnabled: false
sensorPin: 3
systemMessage: system message
systemUpTime: 00:00:00
tempAlertHi: 30.0
tempAlertLo: 13.0
tempSPLOff: 14.5
tempSPLOn: 22.5
ventDisableHumi: 50
ventDisableTemp: 15
ventEnableHighSpeed: true
ventOffDelta: 60000
ventOnDelta: 50000
ventPulseOnDelta: 20000
ventRelay: 26
vent_loff_sp_offset: 1.0
vent_lon_sp_offset: -0.1
version: Version Placeholder
watchDogPin: 17
writingPipeAddress: Node0
zoneName: Zone3
zoneNumber: '3'
