# YAML

#===config params to store in config obj so tunable via web interface====

#Zone 2 - PCDuino
tempSPLOn: 24.0   #target 22.5 mp set point max with lon
tempSPLOff: 21.0 #16.9 #target = 16.9, target loff

lightOnT: "14:00:00"    # time light on hh:mm:ss
lightOffT: "20:00:00"   # time off

## comment out for hardware used as appropriate
##platform_name: "RPi2"
#platformName: "PCDuino"
##hardware: "RaspberryPi2"
#hardware: "PCDuino"
#readDelay: 3
#min_CSV_write_interval: 1 * 60 * 1000 #interval min bet csv writes

##----L control params----
#on_hours: [ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,20,21,22,23] #hours when l on
#heat_off_hours: [ 6,7,8,9,10,11,12,13,14,15,16,17 ]   #hours when heater should NOT operate
##tlon_hour: 06
##tlon_minute: 0    # time on
##tloff_hour: 18
##tloff_minute: 0   # time off

#OFF: 1 #state for relay OFF
#ON: 0  #state for on

#testDivisor: 1 #divisor to speed up sequencing to test timings

#heater_on_t: 18 * 1000 / testDivisor  #min time heater is on or off for
#heater_off_t: 113 * 1000 / testDivisor  #min time heater is on or off for
#heater_sp_offset: 0

#ventOnDelta: 3 * 1000 / testDivisor   #duration vent is on in millis
#ventOffDelta: 197 * 1000 / testDivisor  #vent off duration in miili sec
#ventPulseOnDelta: 10 * 1000 #60 secs cooling on delta
#vent_lon_sp_offset: 0.0 #offset
#vent_loff_sp_offset: 1.0 #

#fan_on_t: 29 * 60 * 1000 / testDivisor   #vent on time
##fan_on_t = 30 * 1000 / testDivisor   #vent on time

#fan_off_t: 10 * 1000 / testDivisor #vent off time

#dataPath: "/home/ubuntu/controlleroo/thdata.csv"

#extraPath: "/home/ubuntu/controlleroo/extradata.csv"

#emailEnabled: False

#tSPHi: tempSPLOn
#tSPLo: tempSPLOff

##db params
#db_hostname: "127.0.0.1"
#db_username: "root"
#db_password: "ubuntu"
#db_dbname: "sensordata_db"

#hi_temp_warning: 26.0
#lo_temp_warning: 14.0



#central_db_hostname: "192.168.0.201"
#central_db_username: "myiot"
#central_db_password: "myiot"
#central_db_dbname: "zone2_sensordata_db"
